### ISSUE TITLE
Mirakurun起動時にreniceコマンドでエラー

### ISSUE THREAD

**Issue by rkarsnk** [Chinachu/docker-mirakurun-chinachu#4]
Mirakurun起動時に `renice -n -10 -p 195` でPermission deniedエラーが発生する。

docker特有の問題かもしれませんが、念の為、issueとして上げておきます。

```
2017-04-08T08:21:01.090409316Z  mirakurun-server  0   fork  42   online  0        0s      3%   17.7 MB    disabled 
2017-04-08T08:21:01.090413611Z 
2017-04-08T08:21:01.090629008Z  Use `pm2 show <id|name>` to get more details about an app
2017-04-08T08:21:01.548611227Z [TAILING] Tailing last 15 lines for [mirakurun-server] process (change the value with --lines option)
2017-04-08T08:21:01.554500553Z /usr/local/var/log/mirakurun.stdout.log last 15 lines:
2017-04-08T08:21:01.556056099Z /usr/local/var/log/mirakurun.stderr.log last 15 lines:
2017-04-08T08:21:01.556555600Z 0|mirakuru |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:53:21)
2017-04-08T08:21:01.556736168Z 0|mirakuru |     at Module._compile (module.js:570:32)
2017-04-08T08:21:01.556856971Z 0|mirakuru | Error: Command failed: renice -n -10 -p 195
2017-04-08T08:21:01.556984514Z 0|mirakuru | renice: setpriority: Permission denied
2017-04-08T08:21:01.557101747Z 0|mirakuru | 
2017-04-08T08:21:01.557110918Z 0|mirakuru |     at checkExecSyncError (child_process.js:483:13)
2017-04-08T08:21:01.557235848Z 0|mirakuru |     at Object.execSync (child_process.js:523:13)
2017-04-08T08:21:01.557361525Z 0|mirakuru |     at Object.<anonymous> (/usr/lib/node_modules/mirakurun/lib/server.ts:51:5)
2017-04-08T08:21:01.557371432Z 0|mirakuru |     at Module._compile (module.js:570:32)
2017-04-08T08:21:01.557495566Z 0|mirakuru |     at Object.Module._extensions..js (module.js:579:10)
2017-04-08T08:21:01.557618854Z 0|mirakuru |     at Module.load (module.js:487:32)
2017-04-08T08:21:01.557627755Z 0|mirakuru |     at tryModuleLoad (module.js:446:12)
2017-04-08T08:21:01.557753737Z 0|mirakuru |     at Function.Module._load (module.js:438:3)
2017-04-08T08:21:01.557890736Z 0|mirakuru |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:53:21)
2017-04-08T08:21:01.557900536Z 0|mirakuru |     at Module._compile (module.js:570:32)
```

**Comment by h-mineta** [comment]
[update] Support Alpine Linux 3.6 #5  と合わせてreniceの対応も致しました
